//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sc.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScUtilResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScUtilResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sc.Util.Resources.ScUtilResources", typeof(ScUtilResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string AlphaLevel_High_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_High_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string AlphaLevel_Hint_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_Hint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string AlphaLevel_Low_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_Low_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string AlphaLevel_Medium_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_Medium_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium High.
        /// </summary>
        public static string AlphaLevel_MediumHigh_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_MediumHigh_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Low.
        /// </summary>
        public static string AlphaLevel_MediumLow_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_MediumLow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium To Medium High.
        /// </summary>
        public static string AlphaLevel_MediumMediumHigh_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_MediumMediumHigh_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium To Medium Low.
        /// </summary>
        public static string AlphaLevel_MediumMediumLow_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_MediumMediumLow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Opaque.
        /// </summary>
        public static string AlphaLevel_NearOpaque_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_NearOpaque_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaque.
        /// </summary>
        public static string AlphaLevel_Opaque_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_Opaque_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string AlphaLevel_VeryHigh_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_VeryHigh_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        public static string AlphaLevel_VeryLow_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_VeryLow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Very High.
        /// </summary>
        public static string AlphaLevel_VeryVeryHigh_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_VeryVeryHigh_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Very Low.
        /// </summary>
        public static string AlphaLevel_VeryVeryLow_Name {
            get {
                return ResourceManager.GetString("AlphaLevel_VeryVeryLow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright.
        /// </summary>
        public static string BrightnessLevel_Bright_Name {
            get {
                return ResourceManager.GetString("BrightnessLevel_Bright_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.
        /// </summary>
        public static string BrightnessLevel_Dim_Name {
            get {
                return ResourceManager.GetString("BrightnessLevel_Dim_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string BrightnessLevel_Medium_Name {
            get {
                return ResourceManager.GetString("BrightnessLevel_Medium_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Bright.
        /// </summary>
        public static string BrightnessLevel_MediumBright_Name {
            get {
                return ResourceManager.GetString("BrightnessLevel_MediumBright_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Dim.
        /// </summary>
        public static string BrightnessLevel_VeryDim_Name {
            get {
                return ResourceManager.GetString("BrightnessLevel_VeryDim_Name", resourceCulture);
            }
        }
    }
}
